name: quicktodo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^1.3.3
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^0.14.3
  get: ^4.3.8
  getwidget: ^2.0.4
  google_fonts: ^2.2.0
  hive_flutter: ^1.1.0
  hooks_riverpod: ^1.0.3
  json_serializable: ^5.0.2

dev_dependencies:
  build_runner: ^2.1.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  hive_generator: ^1.1.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/download.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  fonts:
    - family: "OpenSansRegular"
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400

    - family: "OrbitronRegular"
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
          weight: 400
  assets:
    - ./assets/icons/login.png